spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver

client:
  keystore: src/main/resources/shiba-production.jks
  truststore: src/main/resources/shiba-truststore-production.jks

mnit-esb:
  url: https://svcs.dhs.mn.gov/WebServices/Alfresco/CreateDocument

hennepin-email: hhsews@hennepin.us

mail-gun:
  shouldCC: true

feature-flag:
  send-download-alert: on
  submit-via-email: off
  submit-via-api: on
  submit-docs-via-email-for-hennepin: on
  later-docs-feature: off
  later-docs-v2-feature: off
  county-anoka: off
  county-carver: off
  county-clay: off
  county-cook: off
  county-dodge: off
  county-hennepin: on
  county-morrison: off
  county-olmsted: on
  county-ottertail: off
  county-sherburne: off
  county-steele: off
  county-stlouis: off
  county-wabasha: on
  county-wadena: off
  county-waseca: off
  county-wright: on