parsing:
  expeditedEligibility:
    pageInputs:
      assets:
        pageName: liquidAssets
        inputName: liquidAssets
        defaultValue: 0
      income:
        pageName: thirtyDayIncome
        inputName: moneyMadeLast30Days
        defaultValue: 0
      migrantWorker:
        pageName: migrantFarmWorker
        inputName: migrantOrSeasonalFarmWorker
        required: true
      housingCosts:
        pageName: homeExpensesAmount
        inputName: homeExpensesAmount
        defaultValue: 0
      utilityExpensesSelections:
        pageName: utilityPayments
        inputName: payForUtilities
        required: true
  grossMonthlyIncome:
    groupName: jobs
    pageInputs:
      paidByTheHour:
        pageName: paidByTheHour
        inputName: paidByTheHour
      hourlyWage:
        pageName: hourlyWage
        inputName: hourlyWage
      hoursAWeek:
        pageName: hoursAWeek
        inputName: hoursAWeek
      payPeriod:
        pageName: payPeriod
        inputName: payPeriod
      incomePerPayPeriod:
        pageName: incomePerPayPeriod
        inputName: incomePerPayPeriod
  homeAddress:
    pageInputs:
      street:
        pageName: homeAddress
        inputName: streetAddress
      city:
        pageName: homeAddress
        inputName: city
      state:
        pageName: homeAddress
        inputName: state
      zipcode:
        pageName: homeAddress
        inputName: zipCode
  contactInfo:
    pageInputs:
      email:
        pageName: contactInfo
        inputName: email