name: Deploy to demo

on:
  workflow_dispatch:
    inputs: {}

jobs:
  deploy:
    name: Deploy to Aptible demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.0.3
        with:
          key: ${{ secrets.APTIBLE_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.APTIBLE_KNOWN_HOSTS }}
      - name: Generate Aptible branch name
        run: |
          export BRANCH="deploy-$(date "+%s")"
          echo "::set-env name=BRANCH::$BRANCH"
      - name: Push to Aptible remote branch
        run: git push git@beta.aptible.com:mn-shiba-prod/demo.git "master:$BRANCH"
      - name: Install Aptible CLI and deploy to Aptible
        run: |
          wget -O aptible-package https://omnibus-aptible-toolbelt.s3.amazonaws.com/aptible/omnibus-aptible-toolbelt/master/206/pkg/aptible-toolbelt_0.16.5%2B20200508143656~ubuntu.16.04-1_amd64.deb
          sudo dpkg -i aptible-package
          git remote add demo git@beta.aptible.com:mn-shiba-prod/demo.git
          git push demo "master:$BRANCH"
          aptible login --email=${{ secrets.APTIBLE_USERNAME }} --password=${{ secrets.APTIBLE_PASSWORD}}
          aptible deploy --app demo --git-commitish $BRANCH SPRING_PROFILES_ACTIVE=demo 'CLIENT_KEYSTORE-PASSWORD=${{ secrets.CLIENT_KEYSTORE_PASSWORD}}' 'MNIT-ESB_F5-USERNAME=${{ secrets.MNIT_ESB_F5_USERNAME }}' 'MNIT-ESB_F5-PASSWORD=${{ secrets.MNIT_ESB_F5_PASSWORD }}' 'MNIT-ESB_ALFRESCO-USERNAME=${{ secrets.MNIT_ESB_ALFRESCO_USERNAME }}' 'MNIT-ESB_ALFRESCO-PASSWORD=${{ secrets.MNIT_ESB_ALFRESCO_PASSWORD }}'
      - name: Announce on Slack
        if: ${{ always() }}
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }}
          success_text: 'Deploy to Aptible demo succeeded :smile:'
          failure_text: 'Deploy to Aptible demo failed :frowning:'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
