name: Deploy to demo

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release Branch'
        required: true

jobs:
  deploy:
    name: Deploy to Aptible demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - run: git fetch --prune --unshallow
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.0.3
        with:
          key: ${{ secrets.APTIBLE_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.APTIBLE_KNOWN_HOSTS }}
      - name: Generate Aptible branch name
        run: |
          export BRANCH=${{ github.event.inputs.branch }}
          echo "::set-env name=BRANCH::$BRANCH"
      - name: Push to Aptible remote branch
        run: git push git@beta.aptible.com:mn-shiba-prod/demo.git "$BRANCH:$BRANCH"
      - name: Install Aptible CLI and deploy to Aptible
        run: |
          wget -O aptible-package https://omnibus-aptible-toolbelt.s3.amazonaws.com/aptible/omnibus-aptible-toolbelt/master/206/pkg/aptible-toolbelt_0.16.5%2B20200508143656~ubuntu.16.04-1_amd64.deb
          sudo dpkg -i aptible-package
          aptible login --email=${{ secrets.APTIBLE_USERNAME }} --password=${{ secrets.APTIBLE_PASSWORD}}
          aptible deploy --app demo --git-commitish $BRANCH SPRING_PROFILES_ACTIVE=demo \
          'MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}' \
          'SMARTY_STREET_AUTH_ID=${{ secrets.SMARTY_STREET_AUTH_ID }}' \
          'SMARTY_STREET_AUTH_TOKEN=${{ secrets.SMARTY_STREET_AUTH_TOKEN }}' \
          'CLIENT_KEYSTORE-PASSWORD=${{ secrets.CLIENT_KEYSTORE_PASSWORD}}' \
          'MNIT-ESB_USERNAME=${{ secrets.MNIT_USERNAME }}' \
          'MNIT-ESB_PASSWORD=${{ secrets.MNIT_PASSWORD }}' \
          'SHIBA_USERNAME=${{ secrets.SHIBA_USERNAME }}' \
          'SHIBA_PASSWORD=${{ secrets.SHIBA_PASSWORD }}' \
          'ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY_DEMO }}' \
          'SENTRY_DSN=${{ secrets.SENTRY_DSN }}' \
          'SENTRY_ENVIRONMENT=demo' \
          'MIXPANEL_API-KEY=${{ secrets.MIXPANEL_API_KEY_STAGING }}'
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: shiba
        with:
          environment: demo
      - name: Announce on Slack
        if: ${{ always() }}
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }}
          success_text: 'Deploy to Aptible demo succeeded :smile:'
          failure_text: 'Deploy to Aptible demo failed :frowning:'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
