name: Merge Dependabot PR

on:
  workflow_run:
    workflows: ["Run tests"]

jobs:
  merge-dependabot-pr:
    name: Merge Dependabot PR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Artifact from Dependabot Test PR
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          workflow: pr-comment.yml
          name: pr-metadata
      - name: Restore preserved ENV
        run: cat pr.env >> "${GITHUB_ENV}"
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ env.PR_NUMBER }
          recreate: true
          message: |
            @dependabot merge